on:
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.0']
    steps:
      - uses: actions/checkout@v2
        
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 1
          extra-packages: |
            rcmdcheck
        
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
